### ISSUE TITLE
What do you need to finish?

### ISSUE THREAD

**Issue by CHEF-KOCH** [serejandmyself/Privacy-Basics#2]
Hey, 
I saw [your post](https://github.com/serejandmyself/Privacy-Basics) and I was asking myself why do you want to move to PTIO and what do you want to finish here?

**PTIO:**
It's a "die hard" biased and very toxic community, as you saw yourself in the comments. Someone said that Cloudflare as DNS is not "good" but he did not link to an article or reference why. Similar like what they comment on Brave, your suggestions are overall fine and you listed some good tools.

PTIO and other projects need some competition because otherwise people think what they write is 100% _absolute_ (it's not I can tell), so why not continue your own project instead and pick the stuff YOU like and have experience with it instead of listening to random people?

**What do you mean by finish?**
I think tools evolve, and to list some alternatives is not a bad thing, so I ask myself what exactly do you mean by "finish"? You still could continue to work on it, based on latest leaks/findings and update it based on your own experience. 

I think you could also post this on a [GitHub page](https://pages.github.com/) or as already suggested via comments, host it on a small server or personal website and post it there.

**Comment by serejandmyself** [comment]
i guess by "finishing" I meant comments like this. Now, I ain't gonna be biased about all of it. I see you have some excellent points which I can now take, and when I have some spare time - carry on working on this. Thanks

**Comment by serejandmyself** [comment]
Updated repo, added GH pages.
